# Generated by Django 5.0.6 on 2024-05-22 04:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(choices=[('Friesian', 'Friesian'), ('Ayshire', 'Ayshire'), ('Jersey', 'Jersey'), ('Guernsey', 'Guernsey')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 22))])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1)),
                ('availability_status', models.CharField(choices=[('A', 'Alive'), ('D', 'Dead'), ('S', 'Sold')], default='A', max_length=1)),
                ('pregnancy_status', models.CharField(choices=[('P', 'Pregnant'), ('C', 'Calved'), ('N', 'Not pregnant')], default='N', max_length=1)),
                ('date_of_death', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 22))])),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breed', to='dairy.breed')),
                ('calf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calf_of', to='dairy.cow')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calves', to='dairy.cow')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offspring', to='dairy.cow')),
            ],
        ),
    ]
