# Generated by Django 5.0.6 on 2024-05-22 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_time_value', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening'), (4, 'Night')], editable=False)),
                ('milking_date', models.DateTimeField(auto_now_add=True)),
                ('amount_in_kgs', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Amount of milk cannot be less than 0 kgs!'), django.core.validators.MaxValueValidator(35, message='Amount of milk cannot be more than 35 kgs!')], verbose_name='Amount (kg)')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='dairy.cow')),
            ],
            options={
                'verbose_name_plural': 'Milk',
                'unique_together': {('cow', 'milking_time_value')},
            },
        ),
    ]
