# Generated by Django 5.0.3 on 2024-05-23 16:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_milk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='names',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cows', to='dairy.breed'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 23))]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 23))]),
        ),
        migrations.AlterUniqueTogether(
            name='milk',
            unique_together={('cow', 'milking_date', 'milking_time_value')},
        ),
    ]
