# Generated by Django 5.0.3 on 2024-05-24 06:11

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_rename_names_breed_name_alter_cow_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 24))]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 24))]),
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_records', to='dairy.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('date_of_calving', models.DateField(blank=True, null=True)),
                ('pregnancy_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed'), ('Failed', 'Failed')], default='Unconfirmed', max_length=11)),
                ('pregnancy_notes', models.TextField(blank=True)),
                ('calving_notes', models.TextField(blank=True)),
                ('pregnancy_scan_date', models.DateField(blank=True, null=True)),
                ('pregnancy_failed_date', models.DateField(blank=True, null=True)),
                ('pregnancy_outcome', models.CharField(blank=True, choices=[('Live', 'Live'), ('Stillborn', 'Stillborn'), ('Miscarriage', 'Miscarriage')], max_length=11, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies', to='dairy.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Lactation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lactation_number', models.PositiveSmallIntegerField(default=1)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lactations', to='dairy.cow')),
                ('pregnancy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dairy.pregnancy')),
            ],
            options={
                'get_latest_by': '-start_date',
            },
        ),
    ]
